# nodejs already exist in this image
FROM node:20
# create folder + cd folder
WORKDIR /usr/src/app 
# copy nodejs configuration file
COPY ./package.json .
# install express based on package.json file
RUN npm install
# copy the application structure
COPY . .
# let the user know the exatclly port
EXPOSE 3000
# start the application
CMD ["node", "server.js"]




#git clone
#cd respository 
#npm isntall / npm 
#node.\server.js